service: hello-go-lambda

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/main
  events:
    - http:
        path: hello
        method: get
    - stream: arn:aws:dynamodb:ddblocal:000000000000:table/SampleTable
